version: '3'
services:
  redis:
    image: redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
